### PR TITLE
Added podfile support

### PR DESCRIPTION
**Pull request by xavisavvy**

### CODE REVIEW

**Comment by xavisavvy** [comment]
I tried looking for the emails for contributors / authors but didn't see one in the current repo. Feel free to update /add

**Comment by felixLam** [comment]
Hi @xavisavvy,

thank you for your contribution. Would you mind removing the unneeded "template comments and values" such as `# s.screenshots  = "www.example.com/screenshots_1.gif"`.

In general, I am not too sure if this simple framework is really worthwhile to use as a pod rather than as a submodule and directly including the few source files.

**Comment by xavisavvy** [comment]
Sounds good. Extras have been removed. 

Just hoping to reduce cognitive load~ If I see I can use a library with just `pod install ISHLogDNA` I am much more likely to use it over having to do a git submodule, or zip > add to project 

Hope this helps!

**Comment by xavisavvy** [comment]
As a final note for the pod file to work you will need to add the tag '0.0.2' to the repo since the pull request doesn't include tags.

**Comment by shagedorn** [comment]
Just a quick note: We have not forgotten about this and will review/merge it in time. We're currently busy and partly on holidays, hence the delay. We'll also have to claim the pod in trunk.

**Comment by xavisavvy** [comment]
@shagedorn no worries~ Just let me know when and I can transfer it on over~

**Comment by shagedorn** [comment]
We re-implemented this as some of the information had become stale in the meantime (sorry for that, and the long delay in general). Please let us know should you encounter any issues with our implementation.

We'd also appreciate if you could transfer trunk ownership to felix@iosphere.de.

Thanks for your help.

**Comment by shagedorn** [comment]
@xavisavvy Could you please transfer the CocoaPods ownership?

**Comment by felixLam** [comment]
@shagedorn close?

**Comment by shagedorn** [comment]
@xavisavvy …a friendly reminder that we'd appreciate if you transferred the trunk ownership of our library to felix@iosphere.de within the next week. Thank you :)

**Pull request closed without merging**
